- name: create ec2 and r53 resources
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0210f9e4d70e692c9
    security_group: sg-0844feaeae9d1329b
    image_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install backend library
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - botocore
    - boto3
  - name: create ec2 resources
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ security_group }}"
      image_id: "{{ image_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info


  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print ip adress
    ansible.builtin.debug:
      msg: "IP address of {{ item.item }} is {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  